{{- if and .Values.monitoring.enabled .Values.grafana.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubecent.fullname" . }}-grafana-pvc
  namespace: {{ .Values.monitoring.namespace | default "monitoring" }}
  labels:
    {{- include "kubecent.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  accessModes:
    {{- toYaml .Values.grafana.persistence.accessModes | nindent 4 }}
  {{- if .Values.grafana.persistence.storageClassName }}
  storageClassName: {{ .Values.grafana.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
{{- end }}
