{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubecent.fullname" . }}-grafana-secret
  namespace: {{ .Values.monitoring.namespace | default "monitoring" }}
  labels:
    {{- include "kubecent.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
type: Opaque
data:
  admin-password: {{ .Values.grafana.adminPassword | b64enc }}
{{- end }}
