apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubecent.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecent.labels" . | nindent 4 }}
    component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.backend.nodePort }}
      {{- end }}
  selector:
    {{- include "kubecent.selectorLabels" . | nindent 4 }}
    component: backend

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubecent.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecent.labels" . | nindent 4 }}
    component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.frontend.nodePort }}
      {{- end }}
  selector:
    {{- include "kubecent.selectorLabels" . | nindent 4 }}
    component: frontend
